#!/usr/bin/env bash
# Generate javadoc across the whole estate and write the docs/javadocs.md index.
#
# The owner's documentation verdict (2026-07-14): the living docs are a small set of
# plain documents — the specs catalogue (build_features.py), the Allure summary
# (aggregate_allure.py) and the API's own words: JAVADOC, straight from the code the
# glossary generator used to paraphrase. This script runs `javadoc:javadoc` through
# every workspace reactor (each module keeps its own parent — the aggregators only
# drive the build) and indexes where the generated sites landed.
#
# The HTML lands under each module's target/ (gitignored, rebuilt at will); only the
# INDEX is versioned, so the docs point at a reproducible artifact, not a stale copy.

set -euo pipefail
cd "$(dirname "$0")"

for ws in . ../portal ../formula; do
  [ -x "$ws/mvnw" ] || continue
  echo "javadoc: $(cd "$ws" && pwd)"
  if [ -f "$ws/pom.xml" ]; then
    (cd "$ws" && ./mvnw -q -DskipTests javadoc:javadoc) \
      || echo "WARN: javadoc failed in $ws (see output above); the index will skip it"
  else
    # a workspace without a top-level reactor (formula): each child repo builds alone
    for pom in "$ws"/*/pom.xml; do
      [ -f "$pom" ] || continue
      (cd "$ws" && ./mvnw -q -DskipTests -f "$(basename "$(dirname "$pom")")/pom.xml" \
        javadoc:javadoc) \
        || echo "WARN: javadoc failed for $pom; the index will skip it"
    done
  fi
done

{
  echo "# Javadoc — the API in its own words"
  echo
  echo "Generated by \`build_javadocs.sh\` (run it after a build; the HTML lives under"
  echo "each module's \`target/site/apidocs\` — gitignored on purpose, this index is"
  echo "the versioned map). Paths are relative to \`Documents/git/\`."
  echo
  # both plugin layouts: classic target/site/apidocs and the newer target/reports/apidocs
  find . ../portal ../formula \( -path "*/target/site/apidocs/index.html" \
                                 -o -path "*/target/reports/apidocs/index.html" \) \
       2>/dev/null | sort | while read -r idx; do
      mod="${idx%/target/*/apidocs/index.html}"
      rel=$(realpath --relative-to=.. "$idx")
      mod_rel=$(realpath --relative-to=.. "$mod")
      echo "- \`$mod_rel\` → [\`$rel\`]($rel)"
    done
} > docs/javadocs.md

echo "index: docs/javadocs.md"
